[package]
name = "echo-trails"
version = "0.5.1"
description = "相册APP，记忆的回响，过去的经历像回声一样在徘徊."
authors = ["sugar"]
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[lib]
# The `_lib` suffix may seem redundant but it is necessary
# to make the lib name unique and wouldn't conflict with the bin name.
# This seems to be only an issue on Windows, see https://github.com/rust-lang/cargo/issues/8519
name = "tauri_app_lib"
crate-type = ["staticlib", "cdylib", "rlib"]

[build-dependencies]
tauri-build = { version = "2", features = [] }

[dependencies]
tauri = { version = "2", features = [] }
tauri-plugin-shell = "2"
serde = { version = "1", features = ["derive"] }
serde_json = "1"
tauri-plugin-http = { version = "2", features = ["unsafe-headers"] }
tauri-plugin-os = "2"
tauri-plugin-dialog = "2"
tauri-plugin-fs = "2.2.0"
log = "0.4.21"
tauri-plugin-log = "2"
aws-sdk-s3 = "0.28.0"
aws-config = "0.55.3"
tokio = { version = "1.28.0", features = ["full"] }
dotenv = "0.15.0"
tauri-plugin-store = "2"
tauri-plugin-clipboard-manager = "2.3.2"
tauri-plugin-opener = "2"
reqwest = { version = "0.12", default-features = false, features = ["stream", "rustls-tls"] }
futures-util = "0.3"
md5 = "0.7"
tokio-util = { version = "0.7.18", features = ["io", "codec"] }

[target.'cfg(target_os = "android")'.dependencies]
jni = "0.21"
ndk-context = "0.1"

