# 相册账户名，多个子账号可共享相册的管理和查看，这部分是系统账户
sugar = [
    # 子账号配置：主要用于区分不同人对同一账户的操作
    ['sugar', 'token1'],
    ['sugar2', 'token2'],
    ['test', '123'],
]

# 另一个账户：需要的话可以创建多个，数据相互独立
# private = [
#     # 子账号不能重复
#     ['private1', 'token3'],
# ]
